name: TP_KULAS
services:
    mariadb:
        container_name: c_mariadb
        environment:
            - MARIADB_USER=${USER_BD}
            - MARIADB_DATABASE=${NOM_BD}
            - MARIADB_PASSWORD=${USER_PWD}
            - MARIADB_ROOT_PASSWORD=${ROOT_PWD}
        volumes:
            - ./bd_data:/var/lib/mysql
            - ./SQL:/sql
        ports:
            - 3306:3306
        image: mariadb
    monapache_tp:
        container_name: c_monapache_tp
        ports:
            - 80:80
        image: monapache_tp
    phpmyadmin:
        container_name: c_phpmyadmin
        depends_on:
            - mariadb  # ✅ Match the actual MariaDB service name
        environment:
            - PMA_HOST=mariadb  # ✅ Match the service name
        ports:
            - ${PORT_SITE}:80
        image: phpmyadmin
