name: TP_KULAS
services:
    mariadb:
        container_name: c_mariadb
        environment:
            - MARIADB_USER=userbd
            - MARIADB_DATABASE=Pokemon
            - MARIADB_PASSWORD=password
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - ./bd_data:/var/lib/mysql
            - ./SQL:/sql
        ports:
            - 3306:3306
        image: mariadb
    monapache_tp:
        container_name: c_monapache_tp
        ports:
            - 80:80
        image: monapache_tp
    phpmyadmin:
        container_name: c_phpmyadmin
        depends_on:
            - mariadb  # ✅ Match the actual MariaDB service name
        environment:
            - PMA_HOST=mariadb  # ✅ Match the service name
        ports:
            - 8080:80
        image: phpmyadmin
